# Generated by Django 5.2.3 on 2025-07-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechnicalIndicator',
        ),
    ]
